app/models.py
class Legislator:
    def __init__(self, id, name):
        self.id = id
        self.name = name


class Vote:
    def __init__(self, id, bill_id):
        self.id = id
        self.bill_id = bill_id


class VoteResult:
    def __init__(self, id, legislator_id, vote_id, vote_type):
        self.id = id
        self.legislator_id = legislator_id
        self.vote_id = vote_id
        self.vote_type = vote_type


class Bill:
    def __init__(self, id, title, sponsor_id):
        self.id = id
        self.title = title
        self.sponsor_id = sponsor_id

app/__init__.py
from flask import Flask
from app.routes.legislator_routes import legislator_bp
from app.routes.bill_routes import bill_bp


# db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')

    # db.init_app(app)

    app.register_blueprint(legislator_bp)
    app.register_blueprint(bill_bp)

    return app

app/routes/bill_routes.py
from flask import Blueprint, render_template
from app.view_models import BillVoteViewModel
from app.database_mock import (
    get_bills, get_bill_by_id,
    get_vote_results_by_bill_id,
    get_legislator_by_id,
    count_vote_types
)


bill_bp = Blueprint('bill', __name__)


@bill_bp.route('/bills')
def bills():
    bill_list = get_bills()
    amount_of_bills = len(bill_list)
    return render_template('bills.html',
                           bill_list=bill_list,
                           amount_of_bills=amount_of_bills)


@bill_bp.route('/bill/<int:id>', methods=['GET'])
def bill(id):
    view_models = []
    vote_results = get_vote_results_by_bill_id(id)
    for vote_result in vote_results:
        legislator = get_legislator_by_id(vote_result.legislator_id)
        new_model = BillVoteViewModel(legislator_name=legislator.name,
                                      legislator_id=legislator.id,
                                      vote_type=vote_result.vote_type)
        view_models.append(new_model)
    return render_template('bill_detail.html',
                           bill=get_bill_by_id(id),
                           view_models=view_models,
                           supports=count_vote_types(vote_results, 1),
                           opositions=count_vote_types(vote_results, 2))

app/routes/legislator_routes.py
from flask import Blueprint, render_template
from app.view_models import VoteResultViewModel
from app.database_mock import (
    get_legislators,
    get_legislator_by_id,
    get_vote_results_by_legislator_id,
    get_vote_by_id,
    get_bill_by_id,
    count_vote_types
)

legislator_bp = Blueprint('legislator', __name__)


@legislator_bp.route('/')
def index():
    legislator_list = get_legislators()
    amount_of_legislators = len(legislator_list)
    return render_template('index.html',
                           legislator_list=legislator_list,
                           amount_of_legislators=amount_of_legislators)


@legislator_bp.route('/legislators/<int:id>', methods=['GET'])
def legislator(id):

    legislator = get_legislator_by_id(id)
    vote_results = get_vote_results_by_legislator_id(id)
    vote_result_view_models = []

    for vote_result in vote_results:
        vote = get_vote_by_id(vote_result.vote_id)
        bill = get_bill_by_id(vote.bill_id)
        new_view = VoteResultViewModel(legislator_name=legislator.name,
                                       bill_id=bill.id,
                                       bill_title=bill.title,
                                       vote_type=vote_result.vote_type)
        vote_result_view_models.append(new_view)

    return render_template('legislator.html',
                           legislator=legislator,
                           supports=count_vote_types(vote_results, 1),
                           opositions=count_vote_types(vote_results, 2),
                           total_votes=len(vote_results),
                           vote_result_view_models=vote_result_view_models)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quorum</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('legislator.index')}}" >Quorum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('legislator.index')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('legislator.index')}}" >Legislators</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('bill.bills')}}">Bills</a>
            </li>
          </ul>
        </div>
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>
    <!-- Bootstrap Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/bill_detail.html
{% extends "base.html" %}
{% block title %}Bill Detail{% endblock %}
{% block content %}

    <div class="container" style="background-color: white">
        <h2 class="mt-3 mb-3">{{ bill.title }}</h2>

        <p>Total votes: {{(supports + opositions)}}</p>
        <p>Supported by {{supports}} legislators.</p>
        <p>Opposed by {{opositions}} legislators.</p>

        <h4 class="mt-3 mb-1">Bill Votes</h4>

        <table class="table">
        <thead>
          <tr>
            <th scope="col">Legislator</th>
            <th scope="col">Vote</th>
          </tr>
        </thead>
        <tbody>

        {% for view_model in view_models %}
            <tr>
            <td><a class="nav-link" href="{{ url_for('legislator.legislator', id=view_model.legislator_id)}}">{{view_model.legislator_name}}</a></td>
            <td>
                {% if view_model.vote_type == 1 %}
                    <button class="btn btn-success btn-sm" disabled>yay</button>
                {% else %}
                    <button class="btn btn-danger btn-sm" disabled>nay</button>
                {% endif %}
            </td>
            </tr>

        {% endfor %}

        </tbody>
      </table>
    </div>
{% endblock %}

app/templates/bills.html
{% extends "base.html" %}
{% block title %}Bills{% endblock %}
{% block content %}

    <div class="container", style="background-color: white">
        <h2 class="mt-3 mb-3">Bills</h2>
        <p>Bills: {{amount_of_bills}} available.</p>

        {% for bill in bill_list %}
            <a class="nav-link" href="{{ url_for('bill.bill', id=bill.id)}}">{{bill.title}}</a>
        {% endfor %}

    </div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block content %}

    <div class="container", style="background-color: white">
        <h2 class="mt-3 mb-3">Legislators</h2>
        <p>Legislators: {{amount_of_legislators}} available.</p>

        {% for legislator in legislator_list %}
            <a class="nav-link" href="{{ url_for('legislator.legislator', id=legislator.id)}}">{{legislator.name}}</a>
        {% endfor %}

    </div>

{% endblock %}

app/templates/legislator.html
{% extends "base.html" %}
{% block title %}Legislator Detail{% endblock %}
{% block content %}

    <div class="container" style="background-color: white">
        <h2 class="mt-3 mb-3">{{ legislator.name }}</h2>

        <p>Total votes: {{total_votes}}</p>
        <p>Supported: {{supports}} Bills.</p>
        <p>Opposed {{opositions}} Bills.</p>

        <h4 class="mt-3 mb-1">Bills Voted</h4>


        <table class="table">
        <thead>
          <tr>
            <th scope="col">Legislator</th>
            <th scope="col">Bill Title</th>
            <th scope="col">Vote</th>
          </tr>
        </thead>
        <tbody>

        {% for view_model in vote_result_view_models %}
            <tr>
            <td>{{ view_model.legislator_name }}</td>
            <td><a class="nav-link" href="{{ url_for('bill.bill', id=view_model.bill_id)}}">{{view_model.bill_title}}</a></td>
            <td>
                {% if view_model.vote_type == 1 %}
                    <button class="btn btn-success btn-sm" disabled>yay</button>
                {% else %}
                    <button class="btn btn-danger btn-sm" disabled>nay</button>
                {% endif %}
            </td>
            </tr>

        {% endfor %}

        </tbody>
      </table>
    </div>
{% endblock %}